### ISSUE TITLE
wish: command to display currently supported file formats

### ISSUE THREAD

**Issue by jeremytammik** [Developer-Autodesk/workflow-curl-view.and.data.api#1]
something along these lines:

```
./viewerAPI auth
```

returns bearer.

a suitable CURL command to return file formats is shown in 'step 4 – upload a file':

https://developer.autodesk.com/api/view-and-data-api/#step-4-upload-a-file

```
curl  -k --header "Authorization: Bearer tMpDT9fGcWsQVd5BG5XUqpYUBbpR" https://developer.api.autodesk.com/viewingservice/v1/supported
```

massage the result returned, e.g. like this in Python:

```
a = {"extensions":["ipt","neu","stla","stl","xlsx","jt","jpg","skp","prt","dwf","xls","png","sldasm","step","dwg","zip","nwc","model","sim","stp","ste","f3d","pdf","iges","idw","dwt","dxf","catproduct","csv","igs","sldprt","cgr","3dm","sab","obj","pptx","cam360","jpeg","bmp","gbxml","exp","ppt","doc","wire","ige","rcp","txt","dae","x_b","3ds","rtf","rvt","g","sim360","iam","asm","dlv3","x_t","pps","session","xas","xpr","docx","catpart","stlb","tiff","nwd","sat","fbx","smb","smt","ifc","dwfx","tif"], ... }

a['extensions'].sort()

for e in a['extensions']: print e,
```

result:
- 3dm 3ds asm bmp cam360 catpart catproduct cgr csv dae dlv3 doc docx dwf dwfx dwg dwt dxf exp f3d fbx g gbxml iam idw ifc ige iges igs ipt jpeg jpg jt model neu nwc nwd obj pdf png pps ppt pptx prt rcp rtf rvt sab sat session sim sim360 skp sldasm sldprt smb smt ste step stl stla stlb stp tif tiff txt wire x_b x_t xas xls xlsx xpr zip

oops, those are too many, both for viewing and extraction only.

to get the viewing ones, filter them like this:

```
channel_mappings = a['channelMapping']
keys = channel_mappings.keys()
keys.sort()
for x in keys:
  if channel_mappings[x].startswith('view'):
    print x,
```

result:
- 3dm 3ds asm cam360 catpart catproduct cgr dae dlv3 dwf dwfx dwg dwt dxf exp f3d fbx g gbxml iam idw ifc ige iges igs ipt jt model neu nwc nwd obj prt rcp rvt sab sat session sim sim360 skp sldasm sldprt smb smt ste step stl stla stlb stp wire x_b x_t xas xpr zip

**Comment by cyrillef** [comment]
there is already a command to call that api
./viewerAPI upload -h

it did not list the result like you do, but it displayed the whole response
I added some code to do what you suggested - see scripts/upload

**Comment by jeremytammik** [comment]
wow, cool, thank you!
